Repository DFHack/df-structures, pull requests merged in 2020-02, with the labels that each got.

#350 Second pass on history events
  df.history.xml
Labels: layout, new types, research

#358 Various fixes
  df.history.xml
  df.military.xml
  df.unit-thoughts.xml
Labels: layout

#359 Identified incident crime, reordered features
  df.history.xml
  df.meeting.xml
  df.ui.xml
  df.world.xml
Labels: enums, layout
